dist: xenial
os: linux
language: ruby
rvm:
 - 2.3.3
cache: bundler
sudo: true
service:
    -docker
before_install:
  - sudo apt-get update  
  - sudo docker pull microsoft/mssql-server-linux  
  - docker run --name dbserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Rsp3cRsp3c' -ti -p 1500:1500 -d microsoft/mssql-server-linux
  - sudo docker inspect dbserver  
